language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
env:
  - LOGLEVEL: "40"
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv sync --dev 
  - pipenv run nose2 -vvv tests.base_app_tests
  - pipenv run nose2 -vvv --with-coverage
  - WITH_INTEGRATION=True LAUNCH_INTEGRATION=True pipenv run nose2 -vvv --with-coverage tests.integration.test_integration
  - "./lintstats.sh"
after_success:
  - coveralls
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  - docker build . -t arxiv/search:${TRAVIS_COMMIT};
    docker push arxiv/search:${TRAVIS_COMMIT}
  - docker build . -t arxiv/search-agent:${TRAVIS_COMMIT} -f ./Dockerfile-agent;
    docker push arxiv/search-agent:${TRAVIS_COMMIT}
