# Provides a stub service for metadata endpoint. This is for integration
# testing only. It should probably be replaced with something a bit lighter
# weight, e.g. using something mockito-esque.
#
# To run:
#
# $ build . -t metadata-stub -f ./Dockerfile-metadata
# $ docker run -it -p 8000:8000 metadata-stub
#
# Should start uWSGI listening on http://localhost:8000

FROM arxiv/base

WORKDIR /opt/arxiv

ADD search /opt/arxiv/search
RUN pip install -U pip

ADD tests/stubs/docmeta.py /opt/arxiv/docmeta.py
ADD tests/data/examples /opt/arxiv/examples
RUN pip install -U pip
RUN pip install flask arxiv-base uwsgi

ENV METADATA_DIR /opt/arxiv/examples

EXPOSE 8000

ENTRYPOINT ["/usr/bin/uwsgi"]
CMD ["--http-socket", ":8000", "-w docmeta.py", "-M", "-t 3000", "--manage-script-name", "--processes", "8", "--threads", "1", "--async", "100", "--ugreen", "--mount", "/=docmeta.py"]
