FROM arxiv/base

# Add Python consumer and configuration.
ADD requirements.txt /opt/arxiv/
ADD app.py /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

ADD schema /opt/arxiv/schema
ADD mappings /opt/arxiv/mappings
ADD tests /opt/arxiv/tests
ADD search /opt/arxiv/search
ADD wsgi.py /opt/arxiv/
RUN pip install nose2 coverage coveralls

ENV ELASTICSEARCH_SERVICE_HOST 127.0.0.1
ENV ELASTICSEARCH_SERVICE_PORT 9200
ENV ELASTICSEARCH_PORT_9200_PROTO http
ENV ELASTICSEARCH_INDEX arxiv
ENV ELASTICSEARCH_USER "elastic"
ENV ELASTICSEARCH_PASSWORD changeme
ENV METADATA_ENDPOINT https://arxiv.org/docmeta/

WORKDIR /opt/arxiv
CMD nose2 -s tests/integration
