# arxiv/search-index
#
# Runtime for bulk indexing of a large number of records. This is not used in
# version 0.1, but is available for exploratory work in Kubernetes.
#
# Expects a path to a list of newline-delimited arXiv IDs (versionless).
#
# Example (local stack):
#
#    $ mkdir /tmp/to_index
#    $ cp arxiv_id_dump.txt /tmp/to_index
#    $ docker run -it --network=arxivsearch_es_stack \
#    >   -v /tmp/to_index:/to_index \
#    >   -e ELASTICSEARCH_HOST=elasticsearch \
#    >   arxiv/search-index /to_index/arxiv_id_dump.txt
#
# See also ELASTICSEARCH_* and METADATA_ENDPOINT parameters, below.

FROM arxiv/base:0.12.1rc2

# Add Python consumer and configuration.
ADD requirements/prod.txt /opt/arxiv/requirements.txt
ADD app.py /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

ADD schema /opt/arxiv/schema
ADD mappings /opt/arxiv/mappings
ADD search /opt/arxiv/search
ADD tests /opt/arxiv/tests
ADD bulk_index.py /opt/arxiv/

WORKDIR /opt/arxiv/

ENV LC_ALL en_US.utf8
ENV LANG en_US.utf8
ENV LOGLEVEL 40
ENV FLASK_DEBUG 1
ENV FLASK_APP /opt/arxiv/app.py

ENV ELASTICSEARCH_SERVICE_HOST 127.0.0.1
ENV ELASTICSEARCH_SERVICE_PORT 9200
ENV ELASTICSEARCH_PORT_9200_PROTO http
ENV ELASTICSEARCH_USER elastic
ENV ELASTICSEARCH_PASSWORD changeme
ENV METADATA_ENDPOINT https://arxiv.org/docmeta_bulk/
ENV METADATA_VERIFY_CERT True

VOLUME /to_index

ENTRYPOINT ["python3.6", "bulk_index.py", "-l"]
