# Run the Flask development server

FROM ubuntu:zesty

RUN apt-get update && apt-get install -y \
    ca-certificates \
    wget \
    gcc \
    g++ \
    libpython3.6 \
    python3.6 \
    python3.6-dev \
    python3.6-venv \
    git \
 && rm -rf /var/lib/apt/lists/*

# Install Python 3.6 and friends.
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

# Add Python consumer and configuration.
ADD requirements.txt /opt/arxiv/
ADD app.py /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

ADD schema /opt/arxiv/schema
ADD mappings /opt/arxiv/mappings
ADD search /opt/arxiv/search
ADD tests /opt/arxiv/tests

WORKDIR /opt/arxiv/

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV LOGLEVEL 10
ENV FLASK_DEBUG 1
ENV FLASK_APP /opt/arxiv/app.py

ENTRYPOINT ["python3.6", "-m", "flask"]
CMD ["run", "-h", "0.0.0.0"]
#CMD /bin/bash
